gapipy/request.py
tests/test_request.py

If `APIRequestor.get` is called with `resource_id=0, uri=None`, it should make
a request for that id instead of raising a ValueError for an empty input.

Check for None values instead of falsy values in GET request validation

---

gapipy/models/price_promotion.py
tests/fixtures.py
tests/test_resources.py

It seemed like the fake 'amount' key that gets [added to nested promotions](https://github.com/gadventures/gapipy/blob/843d473f0301d814a24e46d5f3536f6b46013f71/gapipy/models/price_promotion.py#L22) was not working. When I retrieved stuff through gapipy that key was missing even though it was present in the raw API response.
Just needed to be declared as a field for gapipy to remember to serialize it.
*Might* be related to https://app.getsentry.com/gadventures/gadv-com/group/88033417/
@bartek I messed with your `DUMMY_DEPARTURE` fixture, hope that that is ok (all the other tests still pass.)

Fix missing 'amount' key in promo dict

---

HISTORY.rst
gapipy/__init__.py
gapipy/cache.py

Previously each instantiation would create a `redis.Redis` client which
would create it's own connection pool. This was causing us to run out of
file handles in certain situations.

Adds connection pool sharing in RedisCache

---

gapipy/models/base.py
gapipy/resources/tour/tour_dossier.py

Resources that are referred to from other resources are not inlined in their
entirety. Often, only their `id` and `href` will be inlined, and an extra API
call has to be made in order to retrieve all the data of the subresource.
In gapipy, we abstract over these details, by making all references to
resources either a Resource object, a Query object, or a plain Python list of
Resource objects. Internally, instantiated resources that aren't complete are
considered as "stubs". If a missing field is accessed and the resource is a
stub, then the full resource is fetched in the background, and the data is
returned transparently.
List of non-child resources were not properly instantiated as stubs, which
meant that accessing missing fields would raise an AttributeError, instead of
fetching it …

Resource list stubs

---

gapipy/cache.py
gapipy/query.py
tests/test_cache.py
tests/test_query.py

This removes the need for the cache backends to know anything about the query
data. Prior to this, we were passing data required to generate a cache key to
the backend – this introduces unnecessary state. Instead the `Query` object is
now responsible for generating cache keys (see `query_key`) since it is aware
of all needed data and has always interacted with the cache backends.
This also enables us to get rid of a use of the `current_client` global
variable.
These changes were extracted from https://github.com/gadventures/gapipy/pull/20

Move cache key building from cache module to Query

---

gapipy/resources/tour/itinerary.py

A new feature has been added to gadventures linking dossiers and content
pages; however, we do not want the content pages associated with gapi.
There is a foreign key that exists between contentpages and dossiers,
but since the content pages do not exist in gapi, we need to re-establish
this relationship. We can do that by exposing the dossier_ids on itinerary-highlights.
The information already exists in gapi-layer, it simply needs to be exposed through gapipy.
As we begin to disassociate dossiers, and other structured data, from the api we'll
need to adopt this pattern of loose relationships more frequently.

Add dossier ids to itinerary media and highlights

---

gapipy/query.py
tests/test_query.py

Brief implementation and testing for https://trello.com/c/xBZibxld/590-different-cache-keys-for-live-and-sandbox-data

Updated query_key() to output the key environment

---

gapipy/models/addon.py
gapipy/models/address.py
gapipy/models/base.py
gapipy/models/room.py
gapipy/resources/base.py
gapipy/resources/booking/nationality.py
gapipy/resources/dossier/activity_dossier.py
gapipy/resources/dossier/details.py
gapipy/resources/geo/state.py
gapipy/resources/language.py
gapipy/resources/tour/accommodation.py
gapipy/resources/tour/itinerary.py
gapipy/utils.py
tests/test_resources.py
tests/test_utils.py

In Python 2, the output of `__repr__` must be a byte string, while in Python 3, it must be unicode. Since the string representation of many G API resources contain words in non-English languages, they can contain characters outside of the ASCII range, which raises a UnicodeEncodeError when it is implictly coerced to the default encoding by Python.
The way we ensure the return of a proper string type in Python 2 is by encoding the output to UTF-8. This might not be adequate in all use cases of gapipy, but this is what Django does in its codebase, and this seems like a good default.
@bartek I'm still not 100% sure if this is a good idea, but this fixes some actual bugs (I have included some regression tests).

Force the output of __repr__ to be of the proper string type

---

gapipy/resources/booking/document.py

- API currently has the audience field on the Document resource
and not the Invoice resource (seen in the developer playground)

Add audience field to Document resource

---

gapipy/resources/base.py

Problem was, couldn't get rid of duplicate resource objects in a list using `set`
https://trello.com/c/L6cUSeED

Add `__hash__` method to `Resource`

---

HISTORY.rst
gapipy/__init__.py
gapipy/resources/dossier/activity_dossier.py

**NB: There are probably other things that went into `master` since 2.4.5 besides this bug fix, I just like to add things to HISTORY as they happen. Also, I don't know when this will be release so I've not filled in a date for 2.4.6**
Someone pointed out that the optional activities on gadventures.com are no longer displaying a duration. Seems that the `duration_label` property of an `ActivityDossier` stopped working -- likely due to the 2.0.0 refactor.

Fix ActivityDossier's Duration initialization

---

README.rst
setup.py
tox.ini

Now that we are a real library which supports Python 3.x, we should
include tox as part of the repository. This initial tox.ini file tests
that gapipy is passing tests on Python 2.7, 3.5, and 3.6
README has been amended to include details on how to run tox

Add tox runner and documentation

---

gapipy/models/base.py

This PR fixes an issue preventing partial updates on Resources caused by python being clever (good) and sharing object references.
The issue (using code)
---
```python
import gapipy
gapi = gapipy.Client(application_key=key)
customer = gapi.customer.get(1234)
customer.name['common_name'] = 'New Common Name'
customer.save(partial=True) # doesn't update the resource
```
The reason for the lack of update is because the `name` property is a `dict`. The base `to_dict()` method and the originally saved `_raw_data` share a reference to the same underlying `dict`.
When we modify the `common_name`, what's being changed is the same underlying `dict`. Thus, when we try to `save(partial=True)`, the same locally modified values are compared in `_update`, which results in no difference being found, and …

Use deepcopy to avoid references between data and _raw_data

---

setup.py

When pip installing gapipy it fails due to a missing import.
```
File "/opt/lib/virtualenvs/lumos/local/lib/python2.7/site-packages/gapipy/resources/booking/service.py", line 4, in <module>
from future.utils import with_metaclass
ImportError: No module named future.utils
```
It might make more sense to not have a requirements.txt file and just use this setup.py file so we don't have to maintain two lists of requirements.

Add `future` to requirements in setup.py

---

HISTORY.rst
gapipy/query.py
tests/test_query.py

Adds a regression test and a fix for issue #65.
If you check out 6b45f0a the regression test will fail; 2459788 has the fix, check that out and the test will pass.
NB: I added a note about this in `HISTORY.rst`, but haven't added a version number or release date... needs to be updated when a release happens

Do not recache on `get`

---

gapipy/models/agency_document.py

We need to retrieve the logo in operator and this field is the only
consistent one identifying this.

Add document type to agency_document

---

gapipy/models/addon.py

Just a fix for the regression test introduced in #71 ...
Unfortunately 29f4217610b048b9385cca1d8b980dc55953371e broke the tests on `master` (`test_listing_non_listable_resource_fails` fails because `accommodations` just became listable for sandbox) so the tests on this PR also fail.
If you look at the details of the #71 test run, though, you can see the `DepartureAddonTestCase` test fail. If you check the test run for this PR you can see the  `DepartureAddonTestCase` test is no longer failing.

Fix failing DepartureAddonTestCase tests

---

gapipy/query.py
tests/test_query.py

See issue #76
Prior to this commit, multiple calls to `.filter()` accumulate arguments over time into a dict at `Query._filter`. When "evaluating" those stored filters by calling `.count()` gapipy resets the dict at `Query._filter`. When "evaluating" those stored filters by calling `.all()` gapipy does not reset the cached filter arguments.
Basically what this amounted to was that if I wanted to write some code that does two *unrelated* filtering queries on the same resource I would have to something like one of the following:
- instantiate two separate gapipy clients, one for each query
- do a (meaningless) `.count()` after my first query in order to flush out the old filter arguments
- reach into my gapipy client and modify the `_filter` dict
This commit changes the behaviour of gapipy …

Reset Query._filters when calling .all()

---

gapipy/resources/booking/agent.py

Use the `BaseModel` class to represent the `role` & `phone_numbers` fields. This will enable attribute access semantics for these fields. Before and after usage is as follows:
```python
agent = client.agent.get(1234)
agent.role['id']
agent.phone_numbers[0]['number']
agent.role.id
agent.phone_numbers[0].number
```

Update Agent resource representation

---

gapipy/models/address.py
gapipy/resources/booking/customer.py

This allows `customer.address` fields to be accessible correctly
using the dot (.) attribute syntax, as well as correctly exposing the
State/Country Resources on the `customer.address`
Usage:
```python
from gapipy import Client
client = Client(application_key='your_api_key')
customer = client.customers.get(1234)
customer.address  # returns  a dict
state_id = customer.address['state']['id']
state_name = ... # not possible as the data is not returned / stored as a Model
customer.address # returns the underlying Address model
state_id = customer.address.state.id
state_name = customer.address.state.name
```
Misc: start removing relative imports

Customers.address should use/return the Address BaseModel

---

gapipy/client.py
gapipy/request.py
tests/test_request.py

Included a config option GAPI_UUID that sets the uuid param on every request made to the API

Add ability to include uuid as part of each request

---

README.rst
gapipy/query.py
gapipy/request.py

This helps with debugging through the various G-API caches. @marz619 and I were debugging the cache and being able to throw the `headers={'Some-Header': 'header-value'}` could be helpful in future.
i.e. `gapi.bookings.get(<booking_id>, cached=False, headers={'Some-Header': 'header-value'})`

Add option to include headers in 'GET' requests

---

gapipy/resources/booking/booking.py

This will expose all bookings linked to this one booking in the payload for the API.

Expose Linked Bookings via the API

---

gapipy/resources/tour/departure.py

Remove the deprecated `add_ons` field from the `departure` resource.
The field is no longer served via the API, and was removed in May, 2018.

Remove add_ons from Departure

---

.travis.yml

Not so much trying to speed things up as to provide better visibility into failures at a glance.
Note that this changes the `script` that Travis will run from `setup.py test` to `setup.py nosetests` ... not sure if there was an explicit desire to AVOID using nose in this context, but I WANT to use nose in order to use the same `-A integration!=X` flag that is illustrated in [the gapipy README](https://github.com/gadventures/gapipy#testing)

Split integration tests in Travis into separate jobs

---

.travis.yml
HISTORY.rst
gapipy/__init__.py
gapipy/cache.py

Tests python-redis 2.x & 3.x versions due to `setex` argument order changes between the major versions. We detect the `redis` version on `RedisCache` initialization and store it onto the class, and use that to call the `setex` method with the correct argument order.
* the order of arguments for ``setex`` has changed between 2.x.x & 3.x.x
* redis `2.x.x` setex argument order: `name/key`, `value`, `time/out`
* redis `3.x.x` setex argument order: `name/key`, `time/out`, `value`
* an alternative option would be to use StrictRedis client but this
change _should_ hold us over for now

RedisCache.set fix (setex argument order changed between redis 2.x & 3.x)

---

gapipy/resources/tour/tour_dossier.py
tests/test_live_api.py

This is analogous to the existing `get_trip_detail` method.
The integration tests have been adjusted to use a Tour Dossier instance that does have `categories` defined for it.

Add `get_category` helper method to Tour Dossier resource

---

HISTORY.rst
gapipy/__init__.py
gapipy/resources/tour/tour.py
gapipy/resources/tour/tour_dossier.py
tests/fixtures.py
tests/test_live_api.py

This is preparatory work for the deprecation of the `tour_dossiers.itineraries` field.
**NB: This PR should probably be considered blocked until 4-Nov-2019 when we actually remove the field from the backend API responses.**
---
Prior to the removal on 4-Nov-2019, there _are_ two other dates of significance in this deprecation:
- 1-Aug-2019: the `itineraries` field of `tour_dossiers` _created after this date_ will only ever contain an empty list
- 9-Sep-2019: the `itineraries` field of _all_ `tour_dossiers` will show an empty list
As far as I can tell, the above milestones won't require any changes to gapipy. gapipy seems happy to construct a `TourDossier` instance from a dict containing either:
- an empty list in the `itineraries` field, or
- no `itineraries` field at all

Remove deprecated `tour_dossiers.itineraries` field

---

gapipy/client.py
gapipy/query.py
gapipy/request.py
gapipy/resources/base.py
tests/test_client.py
tests/test_query.py

Similar to what we do for `get` calls: https://github.com/gadventures/gapipy/commit/77ae9e055b26e24dd5438b5b1c1e7856c61a60ce
Basically, I'm after this functionality because I want to do some
testing of the auth ratelimiting of Trip Editor. The idea is that
gapi-layer passes the X-Forwarded-For header along to TE and TE can use
it to derive the actual client IP (to use in ratelimiting counts). The
TE auth endpoint gets hit when we attempt to *create* an oauth token.
I think that some system somewhere along the path is messing with that
header, though. Having the ability to inject my own X-Forwarded-For
header may help figure out what's happening.

Accept additional HTTP headers in `create` calls

---

gapipy/resources/geo/country.py

Just exposing some already-existing data on our `countries` resource (e.g. [`/countries/EG`](https://developers.gadventures.com/playground/countries/EG?env=live))
Aside: initially I had been importing the actual `Continent` and `Place` classes to pass in as the second element of the tuples added to `_resource_fields` ... that resulted in some circular import issues, but poking around in the rest of the codebase I see string references as well. From what I can tell, that seems to work here as well.

Add `countries.{continent,place}` references

---

gapipy/utils.py
tests/test_utils.py

**Why are these methods being moved here?**
They exist in another project which has Django as a dependency. We have a non-Django app which uses these methods and it feels like an over-kill to also include Django libraries when we don't need them. 
**Will these methods be removed from the other project? i.e. `django-gapi-hooked` ?**
Not any time soon. After this PR is merged, I might add a note/comment in the code, but no plans to delete it right now. This is because I don't want to break any other project accidentally. 
**Will the documentation be updated to reflect the existence of these methods here?**
Yes. At least, I'm looking to update these pages;
https://developers.gadventures.com/docs/webhooks.html#registering-a-webhook
https://developers.gadventures.com/docs/webhooks.html#verifyin …

Migrating utility methods from django-gapi-hooked

---

gapipy/query.py
gapipy/resources/base.py
tests/test_query.py
tests/test_resources.py

tl;dr I want better error messages for invalid stubs
This is coming out of some discussions that Craig N and I were having
the other day, but this is an issue that has come up a number of times
sporadically in the past.
Today, gapipy swallows some HTTP errors silently (see
`gapipy.query.HTTPERRORS_MAPPED_TO_NONE`). This behaviour kind of makes
sense for the case where you are explicitly `get`ing that resource,
because you can check for that None condition:
my_departure = g.departures.get(SOME_ID)
if my_departure is None:
pass # or do some things
On the other hand, this behaviour is kind of confusing when you're
working with a stub that is embedded in another resource. For example if
I have a `tour_dossiers` instance and I want the name of the corresponding
booking company, I can do …

Raise an exception when `fetch`ing a stub fails

---

.gitignore
gapipy/query.py
tests/test_query.py

**Task**: [Click](https://app.clickup.com/t/3a949y)
**Description:**  Query methods ( .filter() and .count() ) were clearing _filters attribute which resulted in single usage of a filtered query instance.
**Reproduce**: 
```python
In [3]: reproduce = api.tours.filter(product_line='PPP')
In [4]: reproduce._filters
Out[4]: {'product_line': 'PPP'}
In [5]: reproduce.count()
Out[5]: 1
In [6]: reproduce._filters
Out[6]: {}
In [7]: reproduce.count()
Out[7]: 1249
```
_and_
```python
>>> len([x for x in g.departures.filter(**{'tour_dossier.id': '22758'}).all()])
280
>>> len([x for x in g.departures.filter(**{'structured_itineraries.variation_id': 4364}).all()])
0
```
```python
>>> len([x for x in g.departures.filter(**{'structured_itineraries.variation_id': 4364}).all()])
91
>>> len([x for x in …
```

Improve filtering

---

gapipy/models/base.py
gapipy/request.py
gapipy/resources/base.py
tests/test_request.py

This truly fixes #113. Specifically:
```python
In [5]: len([d for d in g.tour_dossiers.get(24821).departures.filter(start_date__gte='2019-09-20')])
Out[5]: 1247
```
The reason this wasn't working even after #121 was due to the addition of `href` in the call to `requestor.list`: https://github.com/gadventures/gapipy/blob/95a6c4df2348c8340083bc62a8276d8e029fd676/gapipy/query.py#L179-L187
This resulted in the Query filter params being ignored in the `APIRequestor.list_raw` call.
We have modified the `APIRequestor.list_raw` method to check the passed `uri` for a `?`. If found, we will assume that the uri is providing its own query parameters and we will not modify them. Otherwise, we will use the params the requestor was initialised with.

Fix-#121 - modify APIRequestor.list_raw to check the URI for params

---

gapipy/client.py
tests/test_client.py

Add an optional argument to the gapi client that will retry failed queries.  This is useful as a workaround for the frequent timeouts TinCan is facing that result in an empty query being returned. The hope is that on the next try it will complete the query within the alloted time.
Under this hood, this creates a urllib3 `Retry` object in the requests' `HTTPAdapter`.  If someone wanted more granular control, it's totally possible to pass other params like backoff_factor to that object.

Add ability to retry to Client

---

gapipy/resources/tour/tour_dossier.py

Fix broken behaviour from adding `_Parent` namedtuple:
* Adding the `_Parent` namedtuple in models.base broke this existing behaviour when Querying for departures under a tour-dossier. (See https://github.com/gadventures/gapipy/pull/123/commits/53566380a5acc8cfffa88473d6e58a83f4fbbd96)
This borked the following behaviour with an `AttributeError` as noted in https://github.com/gadventures/gapipy/issues/113#issuecomment-616805414
```python
>>> from gapipy import Client
>>> g = Client(application_key="some_api_key")
>>> g.tour_dossiers.get(24821).departures.count()
```
The [`_set_resource_collection_field`](https://github.com/gadventures/gapipy/compare/tour-dossier-departure-query?expand=1#diff-25e4a03badf1a977147e1145fab01b20L48) override in `tour_dossier.py` can be removed as:
1. Tours …

Re: #113 - Fix Tour Dossier Departure nested Query

---

HISTORY.rst
gapipy/resources/tour/_valid_during_range.py
gapipy/resources/tour/departure.py
gapipy/resources/tour/itinerary.py
gapipy/resources/tour/tour_dossier.py
tests/test_resources.py
tests/test_utils.py

Adds `relationships` fields to Both Tour Dossiers and Departures resources.
* `Departure.relationships` exposes related Departures
* `TourDossier.relationships` exposes related Tour Dossiers
* There will always be a correlation between the `departure.relationships[x].departure.tour_dossier` and a `tour_dossier.relationships[y].tour_dossier`.
* NOTE: using x, y as the index ordering may differ
* These relationships have `0..*`association
+ Moves the `ValidDuringRange` into its own file so we can import it into both Resources
+ Any system accessing the `ValidDuringRange` model directly will need to make changes in order to avoid breaking existing code.
+ Replacing existing code:
```python
from gapipy.resources.tour.itinerary import ValidDuringRange
from …
```

Relationships fields for Tour Dossiers & Departures

---

gapipy/cache.py

Source: https://docs.djangoproject.com/en/3.1/topics/settings/#either-configure-or-django-settings-module-is-required

Add pre-configured settings protection

---

gapipy/resources/base.py

The motivation for this PR comes from upgrading the version of gapipy from `2.24.3` to `2.30.1` in another project. I assumed it would be a simple update, but doing so raised multiple unit test errors. 
Some of these errors are caused because of changes in how `fetch()` operates. Take the following code snippet,
```python
self.booking = self.departure_service.booking.fetch()
```
With `2.24.3` , the above would return a booking object.
With `2.30.1` , the above throws an exception - something about invalid remote requests; status 403
My ideal fix for this situation would be to refactor the unit tests so that they no longer make remote requests. Sadly, this would be too time-consuming, so I'm looking for work-arounds. 
The first idea which popped in my head was to bring back the old …

restore old fetch() behaviour

---

gapipy/__init__.py
gapipy/constants.py
gapipy/models/__init__.py
gapipy/models/base.py
gapipy/query.py
gapipy/request.py
gapipy/resources/tour/image.py
gapipy/resources/tour/itinerary.py
gapipy/resources/tour/tour.py
gapipy/resources/tour/tour_dossier.py
tests/test_resources.py

This commit introduces a new constats.py file which can be used by
downstream in their imports. eg;
```
from gapipy.constants import HTTPERRORS_MAPPED_TO_NONE
```
At the moment, no-one downstream needs this, but I'm planning a change
to the fetch() method, where it might be helpful for downstream clients
who want old functionality prior to 2.25.0
ref: #jwuw58

introduce new constants.py file

---

gapipy/cache.py
tests/test_cache.py

I missed this when I implemented the class, so it's more of a bugfix.

Add default timeout support to DjangoCache

---

requirements.txt

We've been using 0.18.2 with this for months on python2, but python 3.8's pip won't let us keep 0.18.2 because gapipy claims it only works with 0.16.0

Make future requirement flexible

---

HISTORY.rst
gapipy/__init__.py
gapipy/resources/tour/departure.py

Adds the `travel_ready_policy` field to the `Departure` Resource.
This field will have two accessible attributes: `code` and `name`
```python
departure = gapi.departures.get(999999)
departure.travel_ready_policy.code
departure.travel_ready_policy.name
```
The currrent set of `code` values will be:
* `COVID_VACCINATED` - Travellers must be fully vaccinated 14 days prior to the start of the departure
* `COVID_VACCINATED_OR_PCR_TEST` - Travellers must be fully vaccinated 14 days prior to the start of the departure OR a negative PCR test within 96 hours (4 days) of the start of the departure.
* `NO_POLICY`
More details can be found on our [developers documentation](https://developers.gadventures.com/docs/departure.html#travel-ready-policy):

Add Departure.travel_ready_policy model field

---

.github/workflows/tox-unit-tests.yml
requirements-testing.txt
setup.py
tests/test_cache.py
tests/test_client.py
tests/test_query.py
tests/test_request.py
tests/test_resources.py
tox.ini

It is currently on `push` and `pull_request` but maybe that's redundant?
2.7 and 3.5 through 3.9 run OK without _too much_ fuss.
Officially, only 3.7+ are supported today, but I know we've got some use-cases that are behind the times.
We're currently using `nose` as our test runner, but it doesn't support 3.10 [0,1,2] -- we'll have to deal with that at some point, but _maaaaybe_ not today? Thoughts?
I'm not sure we use many nose-specific features: some marks to indicate which tests are "integration" and also some parametrization in those integration tests (that we won't run on push/PRs anyway).
pytest is nice, but it doesn't support 2.7.
Oh, I guess nose2 [3] is a thing but I don't know much about it other than that the README claims it supports 2.7 and 3.6-3.10
Seems supported by …

Run unit tests GH Actions with tox

---

HISTORY.rst
gapipy/__init__.py
gapipy/resources/booking/agency_chain.py

The new field contains three attributes; `email`, `phone_number`, and `website_url`; which provide corresponding "contact us" values.
This will be released as version `2.36.0`
NOTE: This field will be `None` (`null`) if all of the contained fields have `None` values.
```python
In [1]: from gapipy import Client
In [2]: gapi = Client(application_key="test_abcd...")
In [3]: ac = gapi.agency_chains.get("a1234000000ABCDEF4")  # null contact_us
In [4]: ac.contact_us is None
Out [4]: True
In [5]: ac = gapi.agency_chains.get("a1234000000ABCDEF5")  # non-null contact_us
In [6]: ac.contact_us
Out[6]: <gapipy.resources.booking.agency_chain.ContactUs at 0x1053a9760>
In [7]: ac.contact_us.website_url
Out[7]: 'https://www.example.com/contact-us'
In [8]: ac._raw_data['contact_us']
Out[8]:
{'email': …
```

Add "contact_us" model field to the AgencyChain resource

---

gapipy/resources/booking/agency.py

Adds the `abta_number` field to the Agency resource. This is a publicly accessible number assigned to Travel Agents and Tour Operators belong to in the UK.
See: https://en.wikipedia.org/wiki/ABTA_%E2%80%93_The_Travel_Association for more information.
```python
> from gapipy import Client
> 
> api = Client()
> x = api.agencies.get('...')
> print("abta_number: ", x.abta_number)
abta_number:  ASDF
```

Add abta_number to Agency resource

---

.github/workflows/tox-unit-tests.yml
tox.ini

These versions are not supported by GitHub Actions anymore, and so the CI checks always fail.
The same thing will probably happen with Python 3.8. But this should buy us some time until the tests can be rewritten to support more modern version of Python.

Remove unsupported Python versions from testing matrix
