gadventures/gapipy

HISTORY.rst
gapipy/__init__.py
gapipy/resources/__init__.py
gapipy/resources/dossier/__init__.py
gapipy/resources/dossier/accommodation_dossier.py
gapipy/resources/dossier/activity_dossier.py
gapipy/resources/dossier/details.py
gapipy/resources/dossier/place_dossier.py
gapipy/resources/dossier/transport_dossier.py
gapipy/resources/tour/__init__.py
gapipy/resources/tour/itinerary.py
gapipy/utils.py
tests/test_utils.py

* Added duration, price, and location helpers for formatting
various fields in Dossiers and ItineraryComponents
* Separated DossierDetail/DetailType models for reuse
* Added mixins for using the above helpers
* Added OptionalActivity resource model
* Used the DossierDetail for all dossiers with `details`
* Added shared methods for accessing specific details
These changes are intended to support the roll-out of structured
itineraries on our Trip Summary pages, but are also useful for any
clients using this library.
https://trello.com/c/LTKlD6Ac (private)

Add dossier helpers and OptionalActivity model

---

gapipy/query.py
gapipy/request.py
tests/test_query.py
tests/test_request.py

Split the URL building, headers gathering and actual request to the API into three different methods.

Refactor request

---

gapipy/resources/tour/promotion.py
tests/test_resources.py

Promotion.products contains a list of objects that represent resources in the
API.
However, there are certain fields (`type`, `sub_type`) which are referenced
within those objects but they do not actually live within the resource.
Because gapipy defines allowed fields, those are lost upon fetch, and this
causes errors for clients which may cache, and then expect that field to
continue to exist.
The solution until the API is changed is to wrap this list of products in a
model that derives its fields from the `type` of product, and then explicitly
adds `type` and `sub_type` to its list of fields.

Add PromotionProduct in order to properly handle Promotion products

---

gapipy/models/base.py
gapipy/utils.py
tests/test_utils.py

This utility will save us plenty of time when defining resources that are
heavily nested and won't benefit from having custom model code written.
cc/ @rafikdraoui 
https://trello.com/c/2jSFmK8X/9-utility-function-to-wrap-python-dict-in-a-dot-accessible-dictionnary

Utility function to wrap Python dict in dot-accessible model.

---

gapipy/cache.py
gapipy/query.py
gapipy/request.py
gapipy/resources/base.py
tests/test_cache.py

Also, fetch using the variation_id when it is present.

Disambiguate cached resources by variation_id

---

HISTORY.rst
gapipy/resources/tour/itinerary.py

https://trello.com/c/C3tz9t1t/706-expose-related-tourdossier-in-itinerary
TODO: fill in the real date in `HISTORY.rst`

Add `Itinerary.tour_dossier` field

---

README.rst

... because it is broken if you are using multiple languages right now.
cc @bartek

Add warning to README re: connection pooling

---

gapipy/cache.py

One could argue that there are some breaking changes since unused functions have been removed and an internal instance attribute as been renamed, but since there were internals and not exposed, I don't believe this needs a version bump. In any case, we can wait to push this change to PyPI until a "real" update is made to `gapipy`, and roll-up a few changes into one version update.

Clean up `cache` module

---

HISTORY.rst
gapipy/__init__.py
gapipy/resources/tour/itinerary.py

And bump version to 2.2.2
https://trello.com/c/JFmMfNXF

Add itinerary day label

---

gapipy/resources/__init__.py
gapipy/resources/dossier/__init__.py
gapipy/resources/dossier/service_level.py
tests/test_live_api.py

ServiceLevel resource accessible through Client

add service_level resource

---

gapipy/resources/__init__.py
gapipy/resources/booking/booking.py
gapipy/resources/checkin/__init__.py
gapipy/resources/checkin/checkin.py
tests/test_live_api.py

add checkins resource for GoodToGo

---

.gitignore
gapipy/resources/dossier/accommodation_dossier.py
gapipy/resources/dossier/activity_dossier.py
gapipy/resources/dossier/country_dossier.py
gapipy/resources/dossier/place_dossier.py
gapipy/resources/dossier/transport_dossier.py

The Dossier's `publish_state` was exposed in `gapi-layer`. Had to also add it here

Add Dossier `publish_state`

---

gapipy/request.py

fixes these errors
https://sentry.io/gadventures/gadv-com/issues/184661122/
https://sentry.io/gadventures/gadv-com/issues/184655302/

fix that accomidates profiles resource's overrides

---

gapipy/resources/geo/place.py

https://trello.com/c/NIF7lzQO/1141-sieve-should-calculate-and-expose-the-amount-of-times-a-place-has-been-referenced-by-all-dossier-types

Add places.dossier_count

---

tests/test_resources.py

Currently, if you instantiate a `Departure` with addons of differing product types (e.g. "accommodations", "activities", "transports") you will notice that all of your `departures.addons.product` are using the same model class.
For example:
>>> [a.product for a in gapi.departures.get(745253).addons]
[<Accommodation: Hotel Boulevard>,
<Accommodation: Cosmos Hotel>,
<Accommodation: Serengeti Balloon Safari>]
... but "Serengeti Balloon Safari" is not an accommodation, it's an activity

Add regression test for departures.addon.product model

---

gapipy/resources/booking/booking.py

Trello: https://trello.com/c/3QEroVf4/1271-gapi-layer-drf-provide-a-way-to-get-all-bookings-of-an-agency

Add `bookings.agency`

---

gapipy/__init__.py
gapipy/resources/booking/agency.py
gapipy/resources/booking/agency_chain.py

Required for agencies now, not having this makes tests fail.
- passenger_notifications
- agent_notifications

Add the communication preferences to agency_chain

---

README.rst
gapipy/query.py
gapipy/request.py
gapipy/resources/base.py

- The assert method string is a bit long now, not sure if gapipy is
strict about line lengths so I've left it.

Adding the ability to make options requests

---

gapipy/models/incomplete_requirement.py

https://trello.com/c/dfjKnnAU/1316-expose-requirement-category-on-incomplete-requirements
Requires: gadventures/gapi-layer-drf#234

IncompleteRequirements now has a requirement_set field.

---

gapipy/models/price_promotion.py

And adds the `amount` field to the _price_fields
NOTE: the use of get_resource_class_from_class_name is intentional
to ensure we import the correct class for subclassing

PricePromotion inherits from Promotion

---

gapipy/resources/booking/agency.py

Add `preferred_display_name` field to Agency

Add preferred_display_name to fields list for agency

---

gapipy/resources/__init__.py
gapipy/resources/base.py
gapipy/resources/booking/agency_chain.py
gapipy/resources/booking_company.py
gapipy/resources/product.py
gapipy/resources/tour/accommodation.py
gapipy/resources/tour/activity.py
gapipy/resources/tour/departure.py
gapipy/resources/tour/promotion.py
gapipy/resources/tour/single_supplement.py
gapipy/resources/tour/tour_dossier.py
gapipy/resources/tour/transport.py

and attach it as a resource collection field to all Product subclasses:
* Accommodation
* Activity
* AgencyChain
* Departure
* SingleSupplement
* TourDossier
* Transport
misc:
* cleanup imports
* minor refactor (move `Product` into its own file)

Add BookingCompany resource

---

gapipy/resources/booking/booking.py

Added customers to the bookings resource as a nested resource.

customers as nested resource on bookings

---

gapipy/query.py
gapipy/resources/__init__.py
gapipy/resources/booking/__init__.py
gapipy/resources/booking/agency_chain.py
gapipy/resources/booking/booking.py
gapipy/resources/booking/checkin.py
gapipy/resources/booking/document.py
gapipy/resources/booking/requirement.py
gapipy/resources/checkin/__init__.py

Adds `requirements` list under the `Booking` resource.
**Defines two new _private_ resources:**
1. `RequirementSet`: returned as a list via `booking/{id}/requirements` or queryable as individual objects
2. `Requirement`: found as individual components within a `RequirementSet`
`Requirements` power G Adventures' [Good-To-Go](https://developers.gadventures.com/docs/goodtogo.html) platform 
**Usage:**
```python
from gapipy import Client
api = Client(application_key='your_application_key')
booking = api.bookings.get(123456)  # <Booking: 123456>
booking_requirements = list(booking.requirements)  # [<RequirementSet: AaBbCcDd (stub)>, ...]
some_requirements = booking_requirements[0].requirements  # [<Requirement: AbcDe12345XyZ (stub)>, ...]
requirement = booking_requirements[0].requirements[0] …
```

Booking Requirements

---

gapipy/resources/tour/departure.py

Adds a `program` field to the Departures resource.

Add a program field to departures payload

---

gapipy/resources/dossier/accommodation_dossier.py
gapipy/resources/dossier/activity_dossier.py
gapipy/resources/tour/departure.py
gapipy/resources/tour/itinerary.py

Add missing/new fields for resources
* Accommodation Dossier
* categories: reference to Tour Categories
* suggested_dossiers: references to Dossiers, but added as `as_is_field`
* visited_countries: reference to Countries
* visited_cities: reference to Places
* Activity Dossier
* suggested_dossiers: references to Dossiers, but added as `as_is_field`
* visited_countries: reference to Countries
* visited_cities: reference to Places
* Departure
* local_payments: Simple model field
* Itinerary
* publish_state

Resource field updates

---

HISTORY.rst
gapipy/resources/tour/tour_dossier.py

🚧 Blocked until corresponding backend work is done... 🚧

Add `slug` field to `tour_dossiers`

---

README.rst
gapipy/cache.py
tests/test_cache.py

Provide the option to let Django handle cache configuration instead.
Credit to @jonprindiville for design

DjangoCache Implementation
